/* Abbreviations:
DCMD - DC Motor Driver
VIND - Visual Indicator Light
SLND - Solenoid
LMTS - Limit Switch
POTI - Potentiometer
VMON - Voltage Monitor
BBRK - Beam Break Sensor
*/


#define DCMD_IGNITER_INSERTER_INA_PIN 29
#define DCMD_IGNITER_INSERTER_INB_PIN 31
#define DCMD_IGNITER_INSERTER_PWM_PIN 5
#define DCMD_IGNITER_INSERTER_DGN_PIN 33

#define DCMD_ELEVATOR_INA_PIN 30
#define DCMD_ELEVATOR_INB_PIN 28
#define DCMD_ELEVATOR_PWM_PIN 3
#define DCMD_ELEVATOR_DGN_PIN 32

#define DCMD_BELT_LINEAR_INA_PIN 27
#define DCMD_BELT_LINEAR_INB_PIN 25
#define DCMD_BELT_LINEAR_PWM_PIN 4
#define DCMD_BELT_LINEAR_DGN_PIN 23

#define DCMD_ARM_PITCH_INA_PIN 24
#define DCMD_ARM_PITCH_INB_PIN 26
#define DCMD_ARM_PITCH_PWM_PIN 2
#define DCMD_ARM_PITCH_DGN_PIN 22



#define VIND_ASG_PIN 12
#define VIND_PWR_PIN 13


#define SLND_FRONT_HATCH_PIN 34
#define SLND_LAUNCH_ROD_PIN 49
#define SLND_ROCKET_HATCH_PIN 36
#define SLND_ARM_LATCH_PIN 51


#define LMTS_IGNITER_INSERTER_PIN 35
#define LMTS_ELEVATOR_TOP_PIN 46
#define LMTS_ELEVATOR_BOTTOM_PIN 37
#define LMTS_RAKE_NEAR_PIN 39
#define LMTS_NOSECONE_CLOSURE_PIN 44
#define LMTS_ARM_PITCH_PIN 42
#define LMTS_ARM_YAW_PIN 40
#define LMTS_BELT_LINEAR_NEAR_PIN 43
#define LMTS_BELT_LINEAR_FAR_PIN 41


#define CFSW_PAUSE_ENABLE_PIN 48

#define ENCR_BELT_LINEAR_A_PIN 45
#define ENCR_BELT_LINEAR_B_PIN 47


// Motors
PololuDC Igniter_Inserter_Motor(DCMD_IGNITER_INSERTER_INA_PIN, DCMD_IGNITER_INSERTER_INB_PIN, DCMD_IGNITER_INSERTER_PWM_PIN, DCMD_IGNITER_INSERTER_DGN_PIN);
PololuDC Elevator_Motor(DCMD_ELEVATOR_INA_PIN, DCMD_ELEVATOR_INB_PIN, DCMD_ELEVATOR_PWM_PIN, DCMD_ELEVATOR_DGN_PIN);
PololuDC Belt_Linear_Motor(DCMD_BELT_LINEAR_INA_PIN, DCMD_BELT_LINEAR_INB_PIN, DCMD_BELT_LINEAR_PWM_PIN, DCMD_BELT_LINEAR_DGN_PIN);
PololuDC Arm_Pitch_Motor(DCMD_ARM_PITCH_INA_PIN, DCMD_ARM_PITCH_INB_PIN, DCMD_ARM_PITCH_PWM_PIN, DCMD_ARM_PITCH_DGN_PIN);
Adafruit_MotorShield AFMS = Adafruit_MotorShield(); 
Adafruit_StepperMotor *Arm_Yaw_Stepper = AFMS.getStepper(200, 1);
Adafruit_StepperMotor *Nose_Closure_Stepper = AFMS.getStepper(200, 2);

